### ISSUE TITLE
Getting "RuntimeError: Task got Future <Future pending> attached to a different loop" on Windows

### ISSUE THREAD

**Issue by wookie184** [python-discord/metricity#15]
Running locally on Windows I get this error.
```
metricity.database[24544] INFO Initiating connection to the database
Ignoring exception in on_guild_available
Traceback (most recent call last):
  File "C:\Users\wookie184\AppData\Local\pypoetry\Cache\virtualenvs\metricity-iF629sR3-py3.9\lib\site-packages\discord\client.py", line 373, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\wookie184\Documents\GitHub\metricity\metricity\bot.py", line 218, in on_guild_available
    await db_ready.wait()
  File "c:\users\wookie184\appdata\local\programs\python\python39\lib\asyncio\locks.py", line 226, in wait
    await fut
RuntimeError: Task <Task pending name='discord.py: on_guild_available' coro=<Client._run_event() running at C:\Users\wookie184\AppData\Local\pypoetry\Cache\virtualenvs\metricity-iF629sR3-py3.9\lib\site-packages\discord\client.py:373>> got Future <Future pending> attached to a different loop
```
I don't really know the meaning of that beyond what it says, although changing the start function in `__main__.py` to this seemed to fix it:
```py
def start() -> None:
    """Start the Metricity application."""
    loop = asyncio.get_event_loop()
    loop.run_until_complete(bot.start(BotConfig.token))
```
I'm take a guess it's something to do with
```python
sync_process_complete = asyncio.Event()
channel_sync_in_progress = asyncio.Event()
db_ready = asyncio.Event()
```
in `bot.py` creating an event loop and then `bot.run` creating a new event loop, but i'm really not sure. Also not sure why it's a windows only thing (guessing it is, since it works on the server).

**Comment by ChrisLovering** [comment]
bit of a long shot, but could you try adding this to the dunder init before anything asyncio related is called. We had to do this in the bots for aiodns on windows, might work here too.
```
if os.name == "nt":
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

**Comment by wookie184** [comment]
> bit of a long shot, but could you try adding this to the dunder init before anything asyncio related is called. We had to do this in the bots for aiodns on windows, might work here too.
> 
> ```
> if os.name == "nt":
>     asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
> ```

That didn't seem to make a difference

**Comment by ChrisLovering** [comment]
> > bit of a long shot, but could you try adding this to the dunder init before anything asyncio related is called. We had to do this in the bots for aiodns on windows, might work here too.
> > ```
> > if os.name == "nt":
> >     asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
> > ```
> 
> That didn't seem to make a difference

![image](https://user-images.githubusercontent.com/9753350/161443905-fadea1e7-a11b-41a4-8e45-9f1e37bf50a9.png)

I'll take a look at it later.

**Comment by ChrisLovering** [comment]
This was because d.py was set to master branch in pyproject.toml, rather than being pinned to a specific version.

The recent asyncio changes in d.py made it incompatible with our current setup.

In the linked PR I pinned d.py to a version before those changes.
