### ISSUE TITLE
Threads archive state is not synchronized after start

### ISSUE THREAD

**Issue by jchristgit** [python-discord/metricity#153]
Currently the thread archive state is only synchronized on startup. This means
that the `archived` flag on threads in the database slowly runs out of sync.

We should probably listen for
[`on_thread_update`](https://discordpy.readthedocs.io/en/stable/api.html#discord.on_thread_update)
or
[`on_raw_thread_update`](https://discordpy.readthedocs.io/en/stable/api.html#discord.on_raw_thread_update)
here and update the database accordingly.

**Comment by ChrisLovering** [comment]
We listen to the former of the two events here https://github.com/python-discord/metricity/blob/main/metricity/exts/event_listeners/guild_listeners.py#L56-L62

Have you seen an example a thread's archive state not being updated? we might need to start listening to the second if so.

I didn't bother listening to the second event originally as my understanding was an active thread should always be in the bot's cache, so archiving a thread should mean that it always triggers the first event.

**Comment by ChrisLovering** [comment]
Just spotted why, https://github.com/python-discord/metricity/pull/156 should fix this

**Comment by ChrisLovering** [comment]
> currently we will synchronize each of the current threads on the guild on any thread update
Yeah just spotted this too, seems quite heavy handed, but as you say it's still a small number of queries as far as postgers is concerned
