### ISSUE TITLE
Users table has all users set to in_guild=False on user upsert

### ISSUE THREAD

**Issue by jchristgit** [python-discord/metricity#157]
When metricity starts up and synchronizes the users, all users temporarily have
their `in_guild` field set to `false`.

From looking at the code I am currently unsure how this can happen. As far as I
understand, the complete upsert is run in a transaction that is committed at
the end of each individual insert.

Demonstration as taken during a metricity restart (whilst `User upsert:`
messages can be seen in the logs):

```sql
metricity=# SELECT in_guild, COUNT(*) FROM users GROUP BY in_guild;  -- During sync
 in_guild | count
----------+--------
 f        | 884763
(1 row)

metricity=# SELECT in_guild, COUNT(*) FROM users GROUP BY in_guild;  -- After sync
 in_guild | count
----------+--------
 f        | 494638
 t        | 390125
(2 rows)
```

**Comment by wookie184** [comment]
Looks like it's currently written to set all to not in the guild, then set those in the guild to true after
https://github.com/python-discord/metricity/blob/e68d83de9bb3027085c4f72e3da4699eefdc1546/metricity/exts/event_listeners/startup_sync.py#L39

**Comment by ChrisLovering** [comment]
https://github.com/python-discord/metricity/pull/159 sems like a way we could fix this. I haven't been able to test that postgres is ok about serialising that many strings in a single query though.

**Comment by ChrisLovering** [comment]
`sqlalchemy.exc.InterfaceError: (sqlalchemy.dialects.postgresql.asyncpg.InterfaceError) <class 'asyncpg.exceptions._base.InterfaceError'>: the number of query arguments cannot exceed 32767` will need to relook at this approach

**Comment by ChrisLovering** [comment]
My only thoughts on how to make the above PR work would be to create a `TEMPORARY` table with `ON COMMIT DROP` and somehow bulk insert all in-guild users into it.

**Comment by wookie184** [comment]
It might be easiest to select all in guild users from the database and then do `db_in_guild - guild.members` and mark them as not in guild with another query.

It's not quite as nice as doing it all on the database but in practice I don't think it makes a difference for our case.

**Comment by wookie184** [comment]
My suggestion was to do the comparison against `guild.members` on the Python side rather than the database site, so basically what we currently do but only change the users we need to. Something like this:
```python
        async with async_session() as sess:
            in_guild_users = await sess.execute(select(models.User).filter_by(in_guild=True)).scalars().all()
            guild_member_ids = {member.id for member in guild.members}

            for user in in_guild_users:
                if user.id not in guild_member_ids:
                    user.in_guild = False

            await sess.commit()
```
