### ISSUE TITLE
Update message on message_edit

### ISSUE THREAD

**Issue by CaedenPH** [python-discord/metricity#22]
As the title specifies, the database should be updated when a user edits their message to ensure accuracy of content.

**Comment by HassanAbouelela** [comment]
We don’t record message content, only message metadata (who sent it, where was it sent, is it deleted, etc)

**Comment by CaedenPH** [comment]
> We don’t record message content, only message metadata (who sent it, where was it sent, is it deleted, etc)

Oops I probably should've read the source code a bit better.
