### ISSUE TITLE
Threads Support

### ISSUE THREAD

**Issue by gdude2002** [python-discord/metricity#9]
Hello! It's me!

I had a quick chat with vco on the DMD last night, and this issue was suggested!

---

Basically, we're using Metricity with Metabase at QuiltMC, but it doesn't have any support for threads. Since we use threads extensively, it'd be outstanding if Metricity was able to track threads in the following capacity:

* Whether a thread is archived or not
* Whether a thread is locked or not
* When the thread was created
* The name of the thread
* What channel a thread belongs to
* What thread a message was sent in (generally it may be best to store both the thread ID and parent channel ID for filtering)

I hear that PyDis may eventually embrace threads, so this may be useful for you in the long run as well.

**Comment by HassanAbouelela** [comment]
Joe’s been working on getting us there, but he’s been trying to work out the details for a while now. @jb3 how far along are we?

**Comment by ChrisLovering** [comment]
I think last time we spoke about it we were talking about a half hack, but thinking on it, full support isn't too hard really.

I may take a look at this later.

**Comment by Akarys42** [comment]
One of the problem mister banks mentioned is to find a way to not store one row per thread, but I personally think that's fine

**Comment by ChrisLovering** [comment]
I was thinking of having another table for threads, something like this ```
class Thread(db.Model):
    """Database model representing a Thread channel."""

    __tablename__ = "threads"

    id = db.Column(
        db.String,
        primary_key=True
    )
    channel_id = db.Column(
        db.String,
        db.ForeignKey("channel.id", ondelete="CASCADE"),
        nullable=False
    )
    name = db.Column(db.String, nullable=False)
    archived = db.Column(db.Boolean, nullable=False)
    locked = db.Column(db.Boolean, nullable=False)
    auto_archive_duration = db.Column(db.Integer, nullable=False)
```

**Comment by Akarys42** [comment]
That seems about right, I would say having the archival time would be also good, and perhaps rename channel_id` to `parent_channel_id`

**Comment by ChrisLovering** [comment]
Yea true. I've been trying to see if thread creation time is surfaced, but I can't seem to find it.

afaik if a thread is from a message, then the thread's ID will be the ID of that message, so you wouldn't be able to use that to work out when it was created.

**Comment by gdude2002** [comment]
> afaik if a thread is from a message, then the thread's ID will be the ID of that message, so you wouldn't be able to use that to work out when it was created.

This is correct, but you could - if the bot's up - supply it based on the creation event?

**Comment by vcokltfre** [comment]
Yeah, it should be fine to just create the thread in the db at the time the event was received by the client notifying it about the thread's creation. It's not going to be 100% accurate to its creation time like a snowflake would be, but I'm not sure a matter of a couple of seconds is that important at the scale of data something like Metricity uses.

**Comment by gdude2002** [comment]
Yeah, it does seem like there's some info lost here, I can't find a specific creation date either. For threads that already exist, it might be OK to assume that the ID is close enough, and then use creation date based on the event where possible.

It'd also be good to have the thread type in the table - so news, public or private

**Comment by ChrisLovering** [comment]
Can threads be news type? I was just gonna have a private boolean flag

**Comment by jb3** [comment]
My original implementation was going to be much less advanced, it was just going to be a new flag on messages which said if a message was in the parent channel or a thread of the parent.

I'm not opposed to storing more though, I think Chris' model looks good.

How are you planning to store thread messages @ChrisLovering, we could tie them to the parent channel and add a nullable FK to the thread and enum for thread message or channel message maybe?

**Comment by ChrisLovering** [comment]
I was going to have a nullable `thread_id` column on `messages`., so the `channel_id` would always be the parent channel in the case of thread messages.

**Comment by gdude2002** [comment]
> Can threads be news type? I was just gonna have a private boolean flag

Yep, all threads created in an announcement channel are news type. There's no real difference other than that the user list contains all the users that could see the announcement channel, so I'm not sure why there's a difference, honestly.

> I was going to have a nullable `thread_id` column on messages. So the `channel_id` would always be the parent channel in the case of thread messages.

This is my preferred approach as well - threads are channels, there is no "thread message" really

**Comment by jb3** [comment]
Do we plan on having Metricity try synchronise thread statuses on startup? I'm not sure how we'd do that in a nice way without iterating all channels, but if we don't then the data stored are possibly out of sync with true Discord state (something we avoid very well for channels)

**Comment by ChrisLovering** [comment]
> Yep, all threads created in an announcement channel are news type. There's no real difference other than that the user list contains all the users that could see the announcement channel, so I'm not sure why there's a difference, honestly.
I'll just have a type column then that stores the enum returned by discord.

> Do we plan on having Metricity try synchronise thread statuses on startup?
Yea, we already iter channels on startup, I was planning on itering threads too

**Comment by jb3** [comment]
> I was going to have a nullable thread_id column on messages. So the channel_id would always be the parent channel in the case of thread messages.

Sounds good - I think it makes sense that we include thread messages in the parent channels by default during aggregations.

**Comment by gdude2002** [comment]
> Yea, we already iter channels on startup, I was planning on itering threads too

It's worth noting that the gateway will give you the active threads - but it won't give you archived or locked threads. Iterating all archived threads is likely to be very expensive.

**Comment by ChrisLovering** [comment]
hmmm, I wonder if _just fine_ to not update archived threads

**Comment by HassanAbouelela** [comment]
Do we need to sync archived threads? Some data would be lost, but I don't think it's too important

**Comment by ChrisLovering** [comment]
Yea, was my thought too.

**Comment by gdude2002** [comment]
Well, it'd be possible to just get the list of active threads and mark the threads that aren't in that list as archived - knowing whether they're locked or not probably isn't too important

**Comment by jb3** [comment]
Yeah, we're probably fine ignoring archived threads, as long as we try our best to capture active threads or archived threads that transition to active.

**Comment by ChrisLovering** [comment]
Yea, archived -> active is fine, as we can listen for the event and they'll be picked up in guild.threads.

active -> archived we'll have to listen to the event _and_ iter through archived threads on ready to ensure we update statuses

**Comment by gdude2002** [comment]
> active -> archived we'll have to listen to the event _and_ iter through archived threads on ready to ensure we update statuses

No, I don't think so - you'd just have to iter the threads in the database and update their flags if they're not in the active list

**Comment by jb3** [comment]
> No, I don't think so - you'd just have to iter the threads in the database and update their flags if they're not in the active list

We can't accurately capture locked here, not sure it particular matters.

**Comment by gdude2002** [comment]
Well, as I said:

> knowing whether they're locked or not probably isn't too important

If you can avoid hitting the Discord API, you should - and there's no need to do so if you have a list of active threads, and a database state listing active and archived threads.

* Get list of active threads from Discord
* Get list of active threads from DB
* For active threads in DB not in list from Discord, mark archived
* Mark all threads from discord as not archived

Really doesn't have to be any more complicated than this

**Comment by vcokltfre** [comment]
There's no need to iterate every channel on startup to find threads anyway, since there's a [`List Active Threads`](List Active Threads) endpoint for guilds which I imagine is implemented. A single call to this endpoint on startup will get every active thread.

**Comment by ChrisLovering** [comment]
> There's no need to iterate every channel on startup to find threads anyway, since there's a [`List Active Threads`](https://discord.com/developers/docs/resources/guild#list-active-threads) endpoint for guilds which I imagine is implemented. A single call to this endpoint on startup will get every active thread.

We already iter all channels on startup since we also sync channels.

I've just hooking into this process and am also itering active threads.

**Comment by gdude2002** [comment]
Thanks for your work on this! One problem - unarchived threads aren't added to the database, and instead throw the following:

![image](https://user-images.githubusercontent.com/204153/147001096-8ca5f849-0549-4c50-8d4b-ce3ceadba641.png)

**Comment by ChrisLovering** [comment]
AH yes! Fixed here https://github.com/python-discord/metricity/pull/12

**Comment by gdude2002** [comment]
That's a lot better, but now it's not setting the `archived` DB field to `true` if I unarchive a thread that was archived before the bot started, and archive it again.

It also seems to be doing a full category and thread sync when I do that?

**Comment by HassanAbouelela** [comment]
The sync function is one big function for everything, so that explains the second part. I'll test the first thing, but the state should be updated whenever an  update event is fired, regardless of previous state.

**Comment by gdude2002** [comment]
I dunno what to tell ya, haha

![image](https://user-images.githubusercontent.com/204153/147002500-af934453-1c93-4407-a2f2-22a7d5fef311.png)

![image](https://user-images.githubusercontent.com/204153/147002561-f3eb043b-171e-4167-92fd-a6ad1b5e7298.png)

**Comment by HassanAbouelela** [comment]
@gdude2002 It's actually not firing off an event at all for the situation you described. I wonder if this is from discord's end, our end, or d.py.

**Comment by gdude2002** [comment]
Discord definitely has an event for this, we have logging bots capturing it. Though, if you're still on vanilla d,py (haven't checked) then I imagine the events may be incorrect

**Comment by gdude2002** [comment]
Looking at how we check for that in KordEx (my framework for Kotlin bots), it looks like it should just be part of the thread object you get as part of the thread update event.

![image](https://user-images.githubusercontent.com/204153/147003242-65174b1e-626e-431a-a24e-9ae9c569d461.png)
